spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grandspace?createDatabaseIfNotExist=true
    password: 
  jpa:
    open-in-view: true

  # security:
  #   user:
  #     name: admin
  #     password: admin@123
